load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "engine",
    srcs = [
        "action_result.py",
        "actions.py",
        "adventure_engine.py",
        "location.py",
        "object.py",
        "scenario.py",
        "scenario_parser.py",
    ],
)
